runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: Mansion/index.html
  upload: Mansion/index.html

- url: /(.*\.(html|js|css|xml))$
  static_files: Mansion/\1
  upload: Mansion/.*\.(html|js|css|xml)$

- url: /.*
  script: main.APP

skip_files:
- Mansion/app
- Mansion/bin
- Mansion/node_modules
- Mansion/obj
- Mansion/release

