# 正規分布の標準偏差
STDDEV=0.3
BIAS=0.1
# 学習率,小さいほど精度があがるが、学習時間が必要
LEARNING_RATE=0.005
HIDDEN_UNIT_SIZE=32
HIDDEN2_UNIT_SIZE=16
TRAINING_COUNT=10000001
python nn_mansion.py mansion.csv $STDDEV $BIAS $LEARNING_RATE $HIDDEN_UNIT_SIZE $HIDDEN2_UNIT_SIZE $TRAINING_COUNT
